2023-06-19 23:08:35 numexpr.utils INFO : Note: NumExpr detected 40 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-06-19 23:08:35 numexpr.utils INFO : NumExpr defaulting to 8 threads.
2023-06-19 23:08:37 align.main INFO : Reading netlist: /home/97ms/uci/ip/dac/2.pre_sim/sw/sw.sp subckt=SW, flat=0
2023-06-19 23:08:37 align.compiler.compiler INFO : Starting topology identification...
2023-06-19 23:08:38 align.cmdline ERROR : Fatal Error. Cannot proceed
Traceback (most recent call last):
  File "/home/97ms/.conda/envs/py3.8/lib/python3.8/site-packages/align/cmdline.py", line 176, in parse_args
    return schematic2layout(**vars(arguments))
  File "/home/97ms/.conda/envs/py3.8/lib/python3.8/site-packages/align/main.py", line 167, in schematic2layout
    primitive_lib = generate_hierarchy(netlist, subckt, topology_dir, flatten, pdk_dir)
  File "/home/97ms/.conda/envs/py3.8/lib/python3.8/site-packages/align/compiler/compiler.py", line 27, in generate_hierarchy
    ckt_data, primitive_library = compiler_input(
  File "/home/97ms/.conda/envs/py3.8/lib/python3.8/site-packages/align/compiler/compiler.py", line 84, in compiler_input
    ckt_data = create_data.read_inputs(design_name)
  File "/home/97ms/.conda/envs/py3.8/lib/python3.8/site-packages/align/compiler/create_database.py", line 33, in read_inputs
    assert top_subckt, f"{name.upper()} not found in library {[e.name for e in self.lib]}"
AssertionError: SW not found in library ['NMOS', 'PMOS', 'CAP', 'RES', 'IND', 'SKY130_FD_PR__PFET_01V8', 'SKY130_FD_PR__NFET_01V8', 'INV']
